name: Publish
on:
  push:
    branches:
      - master
      - scprime

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: test
        run: echo ${{ github.ref }}
      - name: push wallet
        if: ${{ github.ref == '/refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: siacentral/sia-lite-wallet-web:latest
      - name: push scprime
        if: ${{ github.ref == '/refs/heads/scprime' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: siacentral/sia-lite-wallet-web:scprime